#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H

#define BTA_AV_SINK_INCLUDED TRUE
#define BTA_AR_INCLUDED TRUE
#define BTM_DEF_LOCAL_NAME "Echo Show 8"
#define BTA_DM_COD {0x20, 0x04, 0x14}

#endif
